### ISSUE TITLE
Enable analytics tab on dashboard 

### ISSUE THREAD

**Issue by WahdanZ** [parse-community/parse-dashboard#1031]
Enable anyltics tab on dashboard 
is there any why to enable dasboard analytics, i saw there code for it 
https://github.com/parse-community/parse-dashboard/tree/master/src/dashboard/Analytics
also i saw it on back4app so is there any way to enable it on 

- [x] You're running version >=1.2.0 of Parse Dashboard.

- [x] You're running version >=3.1.3 of Parse Server.

**Comment by TomWFox** [comment]
For anyone confused about analytics see [this conversation](https://community.parseplatform.org/t/how-to-use-analytics/328)

As I explained to @WahdanZ analytics is not officially supported or documented. It is possible to link Parse Server with an analytics service with some modification but again this is not documented.

As for Back4App they run a very customised fork of this repo so that is irrelevant in this case.

If anyone wants to make a PR for analytics then please do so but it is not as simple as ‘enabling’ it in the dashboard.
