### ISSUE TITLE
Push Page - Audience Issue

### ISSUE THREAD

**Issue by robertodias180** [parse-community/parse-dashboard#207]
Not sure if this is the intended behaviour or if it is a bug.

I can't crete multiple 'Audience' , and when i leave the push pages the audience i created wont be saved.

It would be nice to be able to create custom audiences to send push easily.

**Comment by drew-gross** [comment]
Thats very true. Unfortunately, saved push audiences requires a place to store the push audiences. Storing them in Parse Server makes sense, but a lot more work is necessary to support that. We'd like to make this happen, but it isn't near the top of our priority list. If you'd like to help, I can give you some pointers!

**Comment by robertodias180** [comment]
I can try building it. What pointer can you give me?

**Comment by dcdspace** [comment]
I also noticed when creating an audience, there is a bug when the installation column type is a Pointer, in which I cannot enter the pointer's objectId. I edited this file `parse-dashboard/src/components/PushAudienceDialog/InstallationCondition.react.js` to present a text box for case Pointer just like String, but it was still not working properly.

**Comment by drew-gross** [comment]
@robertodias180 In Parse Server, you'll need to add a new default class to store push audiences in (with an underscore since it's internal to Parse Server) and make sure it's locked down by default so clients without the master key can't access it. Then, you'll need to modify the dashboard to make use of this new class. There are a lot of things that will need to change for that, because dashboard.parse.com goes thorough special endpoints that don't work with Parse Objects.

@dcdspace can you open a new issue? That is a separate problem from this one.

**Comment by andrew8712** [comment]
Has anybody implemented this?
