### ISSUE TITLE
String filter input field missing

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2131]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
The change in https://github.com/parse-community/parse-dashboard/pull/2059 seems to be causing the filter field to not show.

### Steps to reproduce
See https://github.com/parse-community/parse-dashboard/pull/2059#issuecomment-1126563207

### Actual Outcome
Field not showing

### Expected Outcome
Field should show

### Environment

Dashboard
- Parse Dashboard version: `4.1.2-alpha.1`

**Comment by cyb3rko** [comment]
That's weird, because I only changed the label of the filter, the name is still the same (line 62):

https://github.com/parse-community/parse-dashboard/blob/0615011d88bceb567e2be3119e2e8022ae0c5624/src/lib/Filters.js#L61-L66

And I suppose the lines which add a filter type for the String mode of the filter input are the following:

https://github.com/parse-community/parse-dashboard/blob/0615011d88bceb567e2be3119e2e8022ae0c5624/src/lib/Filters.js#L168-L172

And here the names are used to list the filters, not the labels. I don't get why it doesn't work then.
Line 172 still contains "stringContainsString"

**Comment by mtrezza** [comment]
Well, I think some more investigation is needed, otherwise we'll have to revert the previous PR to not block the beta release.

**Comment by mtrezza** [comment]
Closing via db5d23bf17f65d0db3e5d0d4ef4ca506d8394fb9; reverts https://github.com/parse-community/parse-dashboard/pull/2059.

Revert was done to not block the release pipeline as no-one fixed this issue. @cyb3rko please feel tree to try another attempt and we will gladly review your PR.
