### ISSUE TITLE
Upload App Icon on a App Settings Page

### ISSUE THREAD

**Issue by SaifAlDilaimi** [parse-community/parse-dashboard#369]
I would like to improve #359 and let the user upload a app icon in a "App Settings" menu. Can u guys give me some hints and where to start??

**Comment by drew-gross** [comment]
Sure. The settings pages are currently disabled because they doesn't do anything. You can re-enable the one you need in `DashboardView.react.js` (probably general settings) or create a new settings page. Then, if you enable the general settings page, you'll need to comment out all the parts that don't work, but might in the future (like app name and collaborators) and remove the parts the don't make any sense to keep in Open Source Parse, like Current Plan.

Then you can add a new field using `FileInput`, and create an endpoint in `app.js` to handle the file upload and save the file.

Let me know if you run into any I'm happy to help with environment setup and explaining the abstractions and components we use and so on.
