### ISSUE TITLE
make dashboard readPreference from secondary

### ISSUE THREAD

**Issue by drorsun** [parse-community/parse-dashboard#435]
I would like to be able to configure parse-dashboard to prefer secondary replica-set members in mongo db when scanning for data. I understand this involves integration with the parse-server which is actually holding the connections and doing the queries, but is that somehow possible today?

If not please consider this a feature request.

**Comment by johanarnor** [comment]
@drorsun @flovilmart Any specific reason this was closed? I guess it's possible now, since https://github.com/parse-community/parse-server/pull/3865 is merged? I can take a stab at a PR, if someone guides me in the right direction.

**Comment by johanarnor** [comment]
First, sorry I didn't see that the PR was closed 2 years after opening. Just saw 26 Jun 2016 -> closed on 26 Jun and assumed it was the same year.

Hm, didn't know that thrashing the secondary would severely impact the primary. 
Regarding the solutions:

1. Is it possible to write to the secondary DB as well? I assumed that one could only write to primary in order to not make the DBs out of sync.
2. It's quite wasteful to index every single "column", especially if we need 'createdAt' in the index as well.
3. Will take a look at the maxMs, thanks.
