### ISSUE TITLE
Unauthorized: master key is required

### ISSUE THREAD

**Issue by andrewfelker** [parse-community/parse-dashboard#602]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x ] You're running version >=1.0.19 of Parse Dashboard.

- [x ] You're running version >=2.2.24 of Parse Server.

- [x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

Running Parse Server on Heroku/mlab, trying to run Parse Server Dashboard locally.  

#### Steps to reproduce

I'm now on day 3 of trying to figure out what's wrong with Parse Dashboard, so I'm submitting an issue.  I've followed the steps outlined here: http://blog.parse.com/announcements/introducing-the-parse-server-dashboard/ and here: https://github.com/ParsePlatform/parse-dashboard.  Both ways I end up with a dashboard that reads "Server not reachable: unauthorized: master key is required".  I've checked the parse-server-config.json file many times, tried retyping by hand, validated the JSON, etc, and I still get the same issue.  I've tried using both http and https for the serverURL... You get the picture.  I've run out of ideas.  What's going on here? 

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by flovilmart** [comment]
What does your config look like?

**Comment by andrewfelker** [comment]
Replaced sensitive information with X's. 
{  
   "apps":[  
      {  
         "serverURL":"https://appname.herokuapp.com/parse",
         "appId":"XXXXXXXX",
         "masterKey":"XXXXXXXXX",
         "appName":"xxxxxx"
      }
   ],
   "iconsFolder":"icons"
}

**Comment by flovilmart** [comment]
That's odd indeed

**Comment by flovilmart** [comment]
What version are you running?

**Comment by andrewfelker** [comment]
1.0.19

**Comment by flovilmart** [comment]
Your config seem OK, did your try with a local parse-server and the dashboard referencing it?

**Comment by andrewfelker** [comment]
No, I didn't.  What is the benefit of doing that?

**Comment by flovilmart** [comment]
Make sure you have a local working environment and pinpoint the potential problems

**Comment by andrewfelker** [comment]
Forgive me if I'm missing something.  I started with Parse.com because I'm a front end developer and know very little about backend.  

So I followed the instructions here to run a local parse-server.. https://github.com/ParsePlatform/parse-server-example

But now I don't know the next step for pointing the dashboard to my local parse-server.

**Comment by flovilmart** [comment]
Did you look here: https://github.com/parseplatform/parse-dashboard#local-installation

**Comment by Akath19** [comment]
@flovilmart I'm also getting this with parse-server version 2.5.0 & parse-dashboard version 1.0.24 or 1.0.28, the following is the JSON error in the logs:

`{"error":{"status":403,"message":"unauthorized: master key is required"},"level":"error","message":"Error generating response. { Error: unauthorized: master key is required\n    at promiseEnforceMasterKeyAccess (/home/parse/node_modules/parse-server/lib/middlewares.js:299:17)\n    at /home/parse/node_modules/parse-server/lib/PromiseRouter.js:132:22\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:208:7) status: 403, message: 'unauthorized: master key is required' }"}
Error: unauthorized: master key is required
    at promiseEnforceMasterKeyAccess (/home/parse/node_modules/parse-server/lib/middlewares.js:299:17)
    at /home/parse/node_modules/parse-server/lib/PromiseRouter.js:132:22
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:208:7)
{"error":{"code":119,"message":"Clients aren't allowed to perform the find operation on the installation collection."},"level":"error","message":"Error handling request: ParseError {\n  code: 119,\n  message: 'Clients aren\\'t allowed to perform the find operation on the installation collection.' }"}
{"code":119,"message":"Clients aren't allowed to perform the find operation on the installation collection.","level":"error"}`

This is happening on my local clean install, an OpenShift instance & 2 different DO instances (all clean installs)

**Comment by flovilmart** [comment]
we're running 2.5.0 and dashboard 1.0.28 and don't have the issue, I'm not sure what's wrong @Akath19 without more information. Is your master key correctly set on your dashboard config?

**Comment by Akath19** [comment]
I'm calling it from command line like this:
<img width="508" alt="screen shot 2017-06-28 at 4 46 26 pm" src="https://user-images.githubusercontent.com/3260715/27661889-972e6e06-5c21-11e7-94bc-462545e5a297.png">

**Comment by ksngits** [comment]
I am getting the same error. but the site we built is perfectly working fine and able to access the parse with the same master key.

**Comment by strandedcity** [comment]
I've been spinning on this problem for several days as well, but finally solved it. For me, the issue was that in my _application config_ (nothing to do with dashboard) I had legacy configuration from Parse.com that specified a Client Key, REST Key, and JavaScript Key. Even though these are [no longer required with parse-server](http://docs.parseplatform.org/parse-server/guide/#keys), **they are enforced if you supply them at application init time**. 

However, somewhere between parse-server 2.22.2 and 2.5.3 the behavior changed with regards to the way ACLs are stored in the database for _new_ classes (no effect on the behavior of classes created prior to the change). Supplying _any_ of the keys (REST, Client, or JS) reproduces the behavior described here. Witholding them all fixes the bug. The behavior seems to manifest like this:

**2.22.2**
Supply Keys to app at init time > Create new class > Class is accessible normally via dashboard, and respects CLPs/ACLs

**2.5.3**
Supply Keys to app at init time > Create new class > Class is inaccessible via dashboard (403/unauthorized) *except* when master key is supplied.

There are also differences in the ACLs that I've observed, but I haven't pinned down exactly what the interactions there are.

Hope this is helpful!

**Comment by jblereste** [comment]
> If you can remove the legacy keys (rest, client, and JS), everything will work normally from there on
@strandedcity Thank you it worked 👍 !

I just removed this line from my index.js file:
restAPIKey: process.env.REST_API_KEY || '',

**Comment by ghasempoorm** [comment]
> > If you can remove the legacy keys (rest, client, and JS), everything will work normally from there on
> > @strandedcity Thank you it worked 👍 !
> 
> I just removed this line from my index.js file: restAPIKey: process.env.REST_API_KEY || '',

hello,
can u tell me where is the index.js file?

**Comment by Sky891028** [comment]
Is there a fix plan for this problem in parse-server?
It's definitely a bug

**Comment by mtrezza** [comment]
@Sky891028 According to https://github.com/parse-community/parse-dashboard/issues/602#issuecomment-325128953 it's a matter of documentation. If you see anything to improve in the docs please feel free to open a PR and we'll be glad to review. The issue here is quite old, so the docs issue may not exist anymore, but feel free to take a look.

**Comment by yyman001** [comment]
parse-server:
    depends_on:
      - mongodb
    image: parseplatform/parse-server
    container_name: parse-server
    ports:
      - "127.0.0.1:1337:1337"
    restart: always
    environment:
      PARSE_SERVER_APPLICATION_ID: yyman001
      PARSE_SERVER_MASTER_KEY: abcd1234
      PARSE_SERVER_DATABASE_URI: mongodb://user:pwd@mongodb:27017/dev?authSource=admin
      PARSE_SERVER_MASTER_KEY_IPS: '0.0.0.0/0' #this
